version: '3.1'
services:
  live-preview:
    image: hubci/hugo:0.105
    ports:
      - "1313:1313"
    volumes:
      - "${WORKING_PATH:-./}:/home/circleci/project:rw"
    stop_signal: "${STOP_SIGNAL:-SIGTERM}"
    command: "/usr/bin/hugo server -D --bind=0.0.0.0 --baseURL=http://0.0.0.0 --port=1313"
    user: root
