version: '3.1'
services:
  live-preview:
    image: hubci/hugo:0.105
    ports:
      - "1313:1313"
    volumes:
    - "${WORKING_PATH:-./}:/app:rw"
    stop_signal: "${STOP_SIGNAL:-SIGTERM}"
    command:
    - hugo server -D
    user: root
